title: Data Storytelling (JRNL.3700 s2021) @ Northeastern University
description: Data Storytelling Course (JRNL.3700) - Spring 2021
author: Rahul Bhargava

enableTags: true
tagarray: []

permalink: /:year/:month/:day/:title:output_ext

collections:

social:

share:

urls:
    - text: About
      url: about/

url: "https://dataculturegroup.org"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

theme: jekyll-theme-minimal